server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GabiOneZero/bootCamp-ConfigServer
          default-label: main
          search-paths:
          - '*.yaml'
